### ISSUE TITLE
Review, Formatting

### ISSUE THREAD

**Issue by vr8hub** [villeporte/arthur-machen_the-three-impostors#2]
In general, when an entire element is formatted the same way, then the formatting should be done in CSS. For example, formatting a sentence with a single italiced word: This is a sentence with one _italic_ word.
That would use `<em>` as per normal. But, if the entire paragraph needed to be italicized, then that would normally be done in CSS instead.

- [x] In light of that, for instances where the entire header is italicized or strong, it should be handled in CSS rather than with `<i>` or `<strong>` tags on the paragraph. See, e.g., "The Statement of William Gregg…", etc.
- [x] Also on the William Gregg header, the F.R.S. abbreviation should be tagged, and the header should have a bottom margin of 1em to match the scans.
- [x] The "grimy sash" quote in the prologue is from a poem, so should have verse semantics (and CSS). See SEMoS [7.5](https://standardebooks.org/manual/1.6.4/single-page#7.5).
- [x] There are blockquotes that contain language tags, but the CSS to italicize them isn't present. See SEMoS [8.2.9.6](https://standardebooks.org/manual/1.6.4/single-page#8.2.9.6).
- [x] There are missing thematic breaks, e.g. before "The young lady who called herself Miss Lally began to recite:" in chapter 4. These should be formatted with `<hr/>`; see SEMoS [4.1.1.2.7](https://standardebooks.org/manual/1.6.4/single-page#4.1.1.2.7). You will need to scan the entire book for others. Note that blockquotes already include vertical margin, so no break is needed for them.
- [x] In chapter 3, the paragraph following the "Wholesale lynching" blockquote, i.e. "A Dalziel telegram…", is part of the newspaper cutting and so should be in the blockquote.
- [x] Also on that blockquote, the formatting (in CSS, see the first item above) should be different for the two headers, i.e. the first line should have a larger font size to match the scans. Also, since they're headlines, they should either be titlecase, e.g. Wholesale Lynching (where the lowercase there are smallcaps).
- [x] There are several unsemanticated italics (`<i>`). We use them very rarely, so please review SEMoS [8.2](https://standardebooks.org/manual/1.6.4/single-page#8.2) and add the appropriate semantics. The limestone inscription is the one exception.
- [x] One of those is the double ll's (lowercase L) in chapter-4, but the scans only have a a single l (_l's_) there; see page 94.
- [x] There are multiple tagged words/phrases, e.g. habitué, that are in M-W; see SEMoS [8.2.9.4](https://standardebooks.org/manual/1.6.4/single-page#8.2.9.4). The tags should be removed on those words/phrases.
- [x] _Comédie humaine_, _De situ orbis_, should be tagged as books, retaining their language tags. Books, magazines, etc. are always tagged as such, regardless of language. This includes even fictitious ones, e.g. _Protoplasmic Reversion_. Note that capitalization of non-English titles is different than English ones. Prideaux's _Connection_ should be tagged (and therefore not quoted) as well.
- [x] There are a few cases of semi-colons inside quotes, e.g. ‘…I think not;’. Those should be moved outside of the quotes. Since it is changing the content, it should be an Editorial commit.
- [x] I'm not sure the "versus" in chapter 5 is emphasis; it looks more like italicizing what was then considered a non-English word.
- [x] The letter salutation in chapter 7 is not small-capped.

**Comment by villeporte** [comment]
The only salutation that I can find in chapter 7 is "My Dear Haberden" (p. 172 in the scans, chapter-6.xhtml after renaming), and is not in small caps in the scans nor in the ebook. The only other salutation in the book is "My dear Miss Lally" (p.102) _is_ set in caps in both the scans and the ebook. Should I set the first salutation in small caps?

**Comment by villeporte** [comment]
I've fixed the styling for the parts you mentioned and it looks similar to the scans now. This is the first time I'm writing any CSS code, so it is probably quite hacky, but the builds look OK. 

Also, I forgot to add an editorial tag to a commit message, so had to rebase at some point. Sorry about that!

**Comment by vr8hub** [comment]
Yes, we’re consistent with our letter formatting (see the standard CSS), so both should be small-capped.

**Comment by vr8hub** [comment]
It's quite clever, actually, so good job! :) But, ereaders in general aren't all that current on their HTML/CSS support. Using id's allow us to reduce the complexity of the selectors.

In the case of chapter 3, that blockquote is the only one with a header, and that header only has one paragraph, so the selector can be simpler.
````
/* Applies to William Gregg header */
#chapter-3 blockquote > header{
	font-style: italic;
	margin-bottom: 1em;
}
````

Same for chapter-2; it's the only blockquote, full stop. We want a margin between the header and the text, so we can apply CSS to the header to cover both lines, and then just make the first paragraph (line) slightly larger.
````
/* The two blocks below apply to the headlines in blockquote */
#chapter-2 blockquote > header{
	font-variant: all-small-caps;
	margin-bottom: 1em;
}

#chapter-2 blockquote > header > p:first-of-type{
	font-size: 1.25em;
}
````

I will note that Alex is particular about CSS, so he's likely to change whatever we come up with. :)

Don't forget to run lint and handle whatever it has, if anything, and then run clean when you're finished.

**Comment by vr8hub** [comment]
Sorry, I just noticed that the "Gold Tiberius" blockquote in chapter-7 still has the `<b>` on the paragraph rather than the CSS. You can do the same there as with the others above; this time, since there are two blockquotes, a `first-of-type` is needed on the selector.

````
#chapter-7 blockquote:first-of-type{
        font-variant: small-caps;
}

**Comment by villeporte** [comment]
OK, will make all these changes. I'll have access to my machine again on Friday, so I will wrap it up (styling discussed here and the long description) then and you can give me your final comments. I want to thank you for your patience, I am basically learning how CSS works at the same time as I'm writing the code.

**Comment by vr8hub** [comment]
Hah, no worries, I didn't know _anything_ about CSS when I started producing for SE, and I'm still at an elementary level, I think.

**Comment by vr8hub** [comment]
In what is now chapter 3 (…Missing Brother), the letter sounds are all marked with "phoneme," even when it's just a single letter. There is a different tag for a single letter vs multiple letters. See [SEMoS 8.2.8](https://standardebooks.org/manual/1.6.4/single-page#8.2.8).

**Comment by villeporte** [comment]
I think I've fixed everything raised in this issue. I made a small change for the chap.7 code styling that you suggested
```
#chapter-7 > blockquote:first-of-type{
        font-variant: small-caps;
        text-align: center;
}
```
Without the `>` combinator, it was also selecting the other blockquote and I centered it to match the scans. I've also changed the tags from phoneme to grapheme when it is just a single letter.

**Comment by vr8hub** [comment]
Excellent! Everything looks good.

**Comment by villeporte** [comment]
Thanks!
